commit_message: New translations
append_commit_message: 
files:
  - source: src/main/resources/assets/favorita/lang/en_US.json
    translation:
      - src/main/resources/assets/favorita/lang/%locale_with_underscore%.json
      - src/main/resources/assets/minecraft/lang/%locale_with_underscore%.lang
    update_option: update_as_unapproved
bundles:
  - 4
